### ISSUE TITLE
[warehouse] initialize_demo_db.cpp does not compile with boost-program-options 1.49.0.1

### ISSUE THREAD

**Issue by po1** [moveit/moveit_ros#226]
As pointed out on stackoverflow, an #include is probably missing.
http://stackoverflow.com/questions/13432201/whats-wrong-when-the-compiler-tells-me-a-variable-has-initializer-but-incomple

```
tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp: In function 'int main(int, char**)':
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:54:47: error: aggregate 'boost::program_options::options_description desc' has incomplete type and cannot be defined
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:57:14: error: 'value' is not a member of 'boost::program_options'
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:57:14: note: suggested alternative:
/usr/include/boost/bind/bind.hpp:112:25: note:   'boost::_bi::value'
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:57:55: error: expected primary-expression before '>' token
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:57:57: error: expected primary-expression before ')' token
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:58:14: error: 'value' is not a member of 'boost::program_options'
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:58:14: note: suggested alternative:
/usr/include/boost/bind/bind.hpp:112:25: note:   'boost::_bi::value'
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:58:55: error: expected primary-expression before '>' token
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:58:57: error: expected primary-expression before ')' token
/tmp/buildd/ros-groovy-moveit-ros-warehouse-0.3.25-0wheezy-20130416-2255/warehouse/src/initialize_demo_db.cpp:61:33: error: 'parse_command_line' is not a member of 'boost::program_options'
make[4]: *** [warehouse/CMakeFiles/moveit_init_demo_warehouse.dir/src/initialize_demo_db.cpp.o] Error 1
```
