### ISSUE TITLE
Compilation error on moveit_ros while installing Moveit from source

### ISSUE THREAD

**Issue by karyuv** [moveit/moveit_ros#239]
Hello everyone, I was trying to do source based installation of recently released "Moveit". When the installation reached 61% I am getting the following error:

[ 60%] Building CXX object moveit_ros/planning/trajectory_execution_manager/CMakeFiles/test_controller_manager.dir/test/test_app.cpp.o
Linking CXX shared library /home/karthik/groovy_workspace/moveit/devel/lib/libtest_controller_manager_plugin.so
/home/karthik/groovy_workspace/moveit/src/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp: In member function ‘void planning_scene_monitor::PlanningSceneMonitor::excludeRobotLinksFromOctree()’:
/home/karthik/groovy_workspace/moveit/src/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp:533:10: error: ‘class shapes::Mesh’ has no member named ‘mergeVertices’
[ 60%] Built target test_controller_manager_plugin
Linking CXX executable /home/karthik/groovy_workspace/moveit/devel/lib/moveit_ros_planning/test_controller_manager
[ 60%] Built target test_controller_manager
make[2]: **\* [moveit_ros/planning/planning_scene_monitor/CMakeFiles/moveit_planning_scene_monitor.dir/src/planning_scene_monitor.cpp.o] Error 1
make[1]: **\* [moveit_ros/planning/planning_scene_monitor/CMakeFiles/moveit_planning_scene_monitor.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

I tried uninstalling ROS,reinstalled it again without debian based moveit and it gives the same issue. Please help me on this. 
I am working on *ROS-GROOVY *Ubuntu 12.04

**Comment by isucan** [comment]
Hey, I removed a repo that I thought made it to public -- it seems it has not yet. Just get the rosinstall file again
https://github.com/ros-planning/moveit_docs/blob/master/moveit.rosinstall
please make sure you do not have any moveit debs or geometric_shapes installed, and compile again.

**Comment by karyuv** [comment]
That did the compilation good. But now I am getting new issues which did not get last time(when I was working with earlier versions). This is the new error while trying to run a launch file

[rospack] Error: stack/package pr2_description not found
[librospack]: error while executing command

**Comment by sachinchitta** [comment]
Try sudo apt-get install ros-groovy-pr2-common (that's where the pr2_description package is). Alternatively, if you don't care about the PR2 specific packages, remove moveit_pr2 from your src directory.

**Comment by karyuv** [comment]
Issue solved I installed the pr2-common package all working well now.  Thanks a lot!!
